import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import { ElevaiteIcons, SidebarIconProps } from "@elevaite/ui";
import AppLayout from "../ui/AppLayout";
import { EngineerTheme } from "../ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const breadcrumbLabels: { [key: string]: { label: string; link: string } } = {
  workers_queues: {
    label: "Workers & Queues",
    link: "/workers_queues",
  },
  models: {
    label: "Models",
    link: "/models",
  },
  datasets: {
    label: "Datasets",
    link: "/datasets",
  },
  workbench: {
    label: "Workbench",
    link: "/workbench",
  },
  home: {
    label: "Applications",
    link: "/",
  },
};

const sidebarIcons: SidebarIconProps[] = [
  // { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
  // { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
  // { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
  { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/workbench" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppLayout breadcrumbLabels={breadcrumbLabels} sidebarIcons={sidebarIcons} theme={EngineerTheme}>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
