"""add_roles_groups_tables

Revision ID: 2a407f3f7777
Revises: add_permission_overrides
Create Date: 2026-01-13 16:10:40.233050

This migration adds:
- roles: System-defined and custom roles with base permission types
- role_permissions: Per-service allowed actions for each role
- groups: Organization-defined permission groups
- group_permissions: Per-service allow/deny actions for groups
- user_group_memberships: Maps users to groups on resources

Also updates user_role_assignments to reference roles table and seeds system roles.
"""

from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a407f3f7777"
down_revision: Union[str, None] = "add_permission_overrides"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# System role definitions (from permission matrix)
SYSTEM_ROLES = [
    {"name": "Organization Super Admin", "base_type": "superadmin", "scope_type": "organization"},
    {"name": "Organization Admin", "base_type": "admin", "scope_type": "organization"},
    {"name": "Organization Editor", "base_type": "editor", "scope_type": "organization"},
    {"name": "Organization Viewer", "base_type": "viewer", "scope_type": "organization"},
    {"name": "Account Admin", "base_type": "admin", "scope_type": "account"},
    {"name": "Account Editor", "base_type": "editor", "scope_type": "account"},
    {"name": "Account Viewer", "base_type": "viewer", "scope_type": "account"},
    {"name": "Project Editor", "base_type": "editor", "scope_type": "project"},
    {"name": "Project Viewer", "base_type": "viewer", "scope_type": "project"},
]

ROLE_PERMISSIONS = {
    "superadmin": ["*"],
    "admin": ["create", "edit", "view", "delete", "execute", "approve", "publish"],
    "editor": ["create", "edit", "view", "execute"],
    "viewer": ["view"],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create roles table
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("base_type", sa.String(length=50), nullable=False),
        sa.Column("scope_type", sa.String(length=50), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("base_type IN ('superadmin', 'admin', 'editor', 'viewer')", name="ck_roles_base_type"),
        sa.CheckConstraint("scope_type IN ('organization', 'account', 'project')", name="ck_roles_scope_type"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_roles_is_system", "roles", ["is_system"], unique=False)
    op.create_index("idx_roles_name", "roles", ["name"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_groups_name", "groups", ["name"], unique=False)
    op.create_index("idx_groups_org_name", "groups", ["organization_id", "name"], unique=True)
    op.create_index("idx_groups_organization_id", "groups", ["organization_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("allowed_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_role_permissions_role_id", "role_permissions", ["role_id"], unique=False)
    op.create_index("idx_role_permissions_role_service", "role_permissions", ["role_id", "service_name"], unique=True)
    op.create_index("idx_role_permissions_service", "role_permissions", ["service_name"], unique=False)
    op.create_table(
        "group_permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("allow_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deny_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_group_permissions_group_id", "group_permissions", ["group_id"], unique=False)
    op.create_index("idx_group_permissions_group_service", "group_permissions", ["group_id", "service_name"], unique=True)
    op.create_index("idx_group_permissions_service", "group_permissions", ["service_name"], unique=False)
    op.create_table(
        "user_group_memberships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "resource_type IN ('organization', 'account', 'project')", name="ck_user_group_memberships_resource_type"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "group_id", "resource_id"),
    )
    op.create_index("idx_user_group_memberships_group_id", "user_group_memberships", ["group_id"], unique=False)
    op.create_index(
        "idx_user_group_memberships_resource", "user_group_memberships", ["resource_type", "resource_id"], unique=False
    )
    op.create_index("idx_user_group_memberships_user_id", "user_group_memberships", ["user_id"], unique=False)

    # 6. Update user_role_assignments table
    op.add_column("user_role_assignments", sa.Column("role_id", sa.UUID(), nullable=True))
    op.alter_column("user_role_assignments", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index("idx_user_role_assignments_role_id", "user_role_assignments", ["role_id"], unique=False)
    op.create_foreign_key(
        "fk_user_role_assignments_role_id", "user_role_assignments", "roles", ["role_id"], ["id"], ondelete="CASCADE"
    )

    # 7. Seed system roles and their permissions
    _seed_system_roles()

    # 8. Migrate existing role assignments to use role_id
    op.execute("""
        UPDATE user_role_assignments ura
        SET role_id = r.id
        FROM roles r
        WHERE r.is_system = true
          AND r.base_type = ura.role
          AND r.scope_type = ura.resource_type
    """)

    # 9. Add update triggers
    for table in ["roles", "role_permissions", "groups", "group_permissions"]:
        op.execute(f"""
            CREATE TRIGGER update_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        """)
    # ### end Alembic commands ###


def _seed_system_roles() -> None:
    """Seed the 9 system roles and their permissions."""
    import json

    for role_def in SYSTEM_ROLES:
        role_id = str(uuid.uuid4())

        # Insert role
        op.execute(f"""
            INSERT INTO roles (id, name, description, base_type, scope_type, is_system, created_at, updated_at)
            VALUES (
                '{role_id}',
                '{role_def["name"]}',
                'System-defined {role_def["base_type"]} role for {role_def["scope_type"]} scope',
                '{role_def["base_type"]}',
                '{role_def["scope_type"]}',
                true,
                NOW(),
                NOW()
            )
        """)

        # Insert role permissions for workflow_engine
        actions = ROLE_PERMISSIONS[role_def["base_type"]]
        actions_json = json.dumps(actions)
        op.execute(f"""
            INSERT INTO role_permissions (role_id, service_name, allowed_actions, created_at, updated_at)
            VALUES (
                '{role_id}',
                'workflow_engine',
                '{actions_json}',
                NOW(),
                NOW()
            )
        """)


def downgrade() -> None:
    """Remove roles and groups tables, restore user_role_assignments."""
    # 1. Drop triggers
    for table in ["roles", "role_permissions", "groups", "group_permissions"]:
        op.execute(f"DROP TRIGGER IF EXISTS update_{table}_updated_at ON {table}")

    # 2. Restore user_role_assignments.role values from role_id before dropping
    op.execute("""
        UPDATE user_role_assignments ura
        SET role = r.base_type
        FROM roles r
        WHERE ura.role_id = r.id
          AND ura.role IS NULL
    """)

    # 3. Restore user_role_assignments
    op.drop_constraint("fk_user_role_assignments_role_id", "user_role_assignments", type_="foreignkey")
    op.drop_index("idx_user_role_assignments_role_id", table_name="user_role_assignments")
    op.alter_column("user_role_assignments", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user_role_assignments", "role_id")

    # 4. Drop new tables (in reverse order due to FKs)
    op.drop_index("idx_user_group_memberships_user_id", table_name="user_group_memberships")
    op.drop_index("idx_user_group_memberships_resource", table_name="user_group_memberships")
    op.drop_index("idx_user_group_memberships_group_id", table_name="user_group_memberships")
    op.drop_table("user_group_memberships")

    op.drop_index("idx_group_permissions_service", table_name="group_permissions")
    op.drop_index("idx_group_permissions_group_service", table_name="group_permissions")
    op.drop_index("idx_group_permissions_group_id", table_name="group_permissions")
    op.drop_table("group_permissions")

    op.drop_index("idx_role_permissions_service", table_name="role_permissions")
    op.drop_index("idx_role_permissions_role_service", table_name="role_permissions")
    op.drop_index("idx_role_permissions_role_id", table_name="role_permissions")
    op.drop_table("role_permissions")

    op.drop_index("idx_groups_organization_id", table_name="groups")
    op.drop_index("idx_groups_org_name", table_name="groups")
    op.drop_index("idx_groups_name", table_name="groups")
    op.drop_table("groups")

    op.drop_index("idx_roles_name", table_name="roles")
    op.drop_index("idx_roles_is_system", table_name="roles")
    op.drop_table("roles")
