"""Update models to use SQLAlchemy 2.0 style

Revision ID: 5a78ac8f4024
Revises: 72a50a53308c
Create Date: 2025-04-10 18:46:22.856581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a78ac8f4024'
down_revision: Union[str, None] = '72a50a53308c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
