"""Clean up attribute access

Revision ID: 8634a3e9a06d
Revises: 5a78ac8f4024
Create Date: 2025-04-10 18:55:06.587810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8634a3e9a06d'
down_revision: Union[str, None] = '5a78ac8f4024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
