"""Add is_manager field to user model

Revision ID: 9ee4ca11d13e
Revises: ab45632ebc37
Create Date: 2025-09-13 15:02:33.535507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ee4ca11d13e"
down_revision: Union[str, None] = "ab45632ebc37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_manager", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_manager")
    # ### end Alembic commands ###
