"""add mfa device verification

Revision ID: ab45632ebc37
Revises: cfc33b087ecb
Create Date: 2025-08-13 13:07:08.767600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab45632ebc37'
down_revision: Union[str, None] = 'cfc33b087ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_device_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mfa_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_device_verifications_device_fingerprint'), 'mfa_device_verifications', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_mfa_device_verifications_id'), 'mfa_device_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mfa_device_verifications_id'), table_name='mfa_device_verifications')
    op.drop_index(op.f('ix_mfa_device_verifications_device_fingerprint'), table_name='mfa_device_verifications')
    op.drop_table('mfa_device_verifications')
    # ### end Alembic commands ###
