"""email_mfa_code_and_expiration

Revision ID: cfc33b087ecb
Revises: ebcb98bd47f9
Create Date: 2025-07-15 19:30:22.135501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfc33b087ecb"
down_revision: Union[str, None] = "ebcb98bd47f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email_mfa_code", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("email_mfa_code_expires", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_mfa_code_expires")
    op.drop_column("users", "email_mfa_code")
    # ### end Alembic commands ###
