"""Add email MFA field to user model

Revision ID: ebcb98bd47f9
Revises: 82806d1cb3a9
Create Date: 2025-07-11 19:30:38.871262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebcb98bd47f9"
down_revision: Union[str, None] = "82806d1cb3a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_mfa_enabled", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_mfa_enabled")
    # ### end Alembic commands ###
