## YOUR CODE HERE ##
EXTRACTED_DATA_URI = 'YOUR_EXTRACTED_DATA_URI_PLACEHOLDER'



############## AUTO GENERATED BY ELEVAITE DATA ENGINE BEGIN ###################
# ti: BUILTIN TASK INSTANCE VARIABLE

ti.xcom_push(key='extracted_data_uri', value=EXTRACTED_DATA_URI) # type: ignore
############## AUTO GENERATED BY ELEVAITE DATA ENGINE END ###################
