import type { Metadata } from "next";
import { AppHeader } from "@repo/ui/components";
import "../ui/globals.css";
import "@repo/ui/styles.css";

const headerButtons: { label: string; link: string; key: string }[] = [
  { key: "dashboard", label: "Dashboard", link: "/dashboard" },
  { key: "knowledge", label: "Knowledge Base", link: "/kb" },
  { key: "functions", label: "Functions", link: "/functions" },

  { key: "apps", label: "Apps", link: "/homepage" },
  { key: "users", label: "Users", link: "/users" },
  { key: "configurations", label: "Configurations", link: "/configurations" },
];
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomepageLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return <AppHeader buttons={headerButtons}>{children}</AppHeader>;
}
