import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import { ElevaiteIcons, NavBar, Sidebar } from "@elevaite/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar
          Logo={<ElevaiteIcons.Logo />}
          sidebarIcons={[
            { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
            { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
            { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
            { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/workbench" },
          ]}
        >
          <NavBar breadcrumbItems={[{ label: "WorkBench" }]} user={{ icon: "" }}>
            {children}
          </NavBar>
        </Sidebar>
      </body>
    </html>
  );
}
