import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import { ElevaiteIcons, SidebarIconProps } from "@elevaite/ui";
import Background from "./background";
import AppLayout from "../ui/AppLayout";
import { AppDrawerTheme } from "../ui/themes";
import { userSearchHelper } from "../lib/searchHelpers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ElevAIte",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let results = userSearchHelper("");

  const breadcrumbLabels: { [key: string]: { label: string; link: string } } = {
    appDrawer: {
      label: "Applications",
      link: "/appDrawer",
    },
    home: {
      label: "Applications",
      link: "/",
    },
  };

  const sidebarIcons: SidebarIconProps[] = [
    // { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
    // { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
    // { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
    { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/workbench" },
  ];

  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen bg-[" + AppDrawerTheme.secondary + "] -z-50"}>
        <AppLayout
          Background={<Background />}
          breadcrumbLabels={breadcrumbLabels}
          sidebarIcons={sidebarIcons}
          theme={AppDrawerTheme}
          layout="user"
        >
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
