import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import { ElevaiteIcons, SidebarIconProps } from "@elevaite/ui";
import Background from "./background";
import AppLayout from "../ui/AppLayout";
import { AppDrawerTheme } from "../ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ElevAIte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const breadcrumbLabels: { [key: string]: { label: string; link: string } } = {
    workers_queues: {
      label: "Workers & Queues",
      link: "/workers_queues",
    },
    models: {
      label: "Models",
      link: "/models",
    },
    datasets: {
      label: "Datasets",
      link: "/datasets",
    },
    appDrawer: {
      label: "App Drawer",
      link: "/appDrawer",
    },
  };

  const sidebarIcons: SidebarIconProps[] = [
    { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
    { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
    { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
    { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/appDrawer" },
  ];

  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen bg-[" + AppDrawerTheme.secondary + "] -z-50"}>
        <AppLayout
          Background={<Background />}
          breadcrumbLabels={breadcrumbLabels}
          sidebarIcons={sidebarIcons}
          theme={AppDrawerTheme}
        >
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
