import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../ui/globals.css";
import { ElevaiteIcons, NavBar, Sidebar } from "@elevaite/ui";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const breadcrumbLabels: { [key: string]: { label: string; link: string } } = {
  workers_queues: {
    label: "Workers & Queues",
    link: "/workers_queues",
  },
  models: {
    label: "Models",
    link: "/models",
  },
  datasets: {
    label: "Datasets",
    link: "/datasets",
  },
  workbench: {
    label: "App Drawer",
    link: "/appDrawer",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Sidebar
            Logo={<ElevaiteIcons.Logo />}
            sidebarIcons={[
              { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
              { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
              { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
              { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/appDrawer" },
            ]}
          >
            <NavBar breadcrumbLabels={breadcrumbLabels} user={{ icon: "" }}>
              {children}
            </NavBar>
          </Sidebar>
        </Providers>
      </body>
    </html>
  );
}
