"""add dbos_workflow_id to ingestion_jobs

Revision ID: b628d7292e72
Revises: 
Create Date: 2025-11-24 16:39:33.175187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b628d7292e72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ingestion_jobs table
    op.create_table(
        'ingestion_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('status', sa.VARCHAR(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('callback_topic', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('dbos_workflow_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('result_summary', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###

