"""
SQLModel database models for the Workflow Engine

This package now re-exports all models from workflow-core-sdk.
The PoC no longer defines its own models - it uses the SDK models.
"""

# Re-export everything from the SDK
from workflow_core_sdk.db.models import (
    BaseModel,
    Workflow,
    WorkflowBase,
    WorkflowCreate,
    WorkflowRead,
    WorkflowUpdate,
    ExecutionStatus,
    StepStatus,
    WorkflowExecution,
    WorkflowExecutionBase,
    WorkflowExecutionRead,
    WorkflowExecutionUpdate,
    StepExecution,
    StepExecutionBase,
    StepExecutionRead,
    StepExecutionUpdate,
    StepType,
    StepTypeBase,
    StepTypeCreate,
    StepTypeRead,
    StepTypeUpdate,
    Agent,
    AgentBase,
    AgentCreate,
    AgentRead,
    AgentUpdate,
    AgentToolBinding,
    AgentMessage,
    Prompt,
    PromptCreate,
    PromptRead,
    PromptUpdate,
    AgentExecutionMetrics,
    WorkflowMetrics,
    Tool,
    ToolBase,
    ToolCreate,
    ToolRead,
    ToolUpdate,
    ToolCategory,
    ToolCategoryBase,
    ToolCategoryCreate,
    ToolCategoryRead,
    ToolCategoryUpdate,
    MCPServer,
    MCPServerBase,
    MCPServerCreate,
    MCPServerUpdate,
    MCPServerRead,
    ApprovalRequest,
    ApprovalRequestBase,
    ApprovalRequestRead,
    ApprovalStatus,
)

__all__ = [
    # Base model
    "BaseModel",
    # Workflow models
    "Workflow",
    "WorkflowBase",
    "WorkflowCreate",
    "WorkflowRead",
    "WorkflowUpdate",
    # Execution models
    "ExecutionStatus",
    "StepStatus",
    "WorkflowExecution",
    "WorkflowExecutionBase",
    "WorkflowExecutionRead",
    "WorkflowExecutionUpdate",
    "StepExecution",
    "StepExecutionBase",
    "StepExecutionRead",
    "StepExecutionUpdate",
    # Step registry models
    "StepType",
    "StepTypeBase",
    "StepTypeCreate",
    "StepTypeRead",
    "StepTypeUpdate",
    # Agent models
    "Agent",
    "AgentBase",
    "AgentCreate",
    "AgentRead",
    "AgentUpdate",
    "AgentToolBinding",
    # Messages
    "AgentMessage",
    # Prompt models
    "Prompt",
    "PromptCreate",
    "PromptRead",
    "PromptUpdate",
    # Approvals
    "ApprovalRequest",
    "ApprovalRequestBase",
    "ApprovalRequestRead",
    "ApprovalStatus",
]
