"""Initial Migration

Revision ID: 44c513fa7758
Revises: 
Create Date: 2024-02-14 16:56:01.486662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c513fa7758'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('applicationType', sa.Enum('INGEST', 'PREPROCESS', name='applicationtype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_step_data',
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('pipeline_step_dependencies',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['pipeline_steps.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entry', sa.String(), nullable=True),
    sa.Column('exit', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entry'], ['pipeline_steps.id'], ),
    sa.ForeignKeyConstraint(['exit'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('startTime', sa.String(), nullable=True),
    sa.Column('endTime', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'FAILED', 'COMPLETED', name='instancestatus'), nullable=True),
    sa.Column('datasetId', sa.String(), nullable=True),
    sa.Column('selected_pipeline_id', sa.String(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['selected_pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instance_chart_data',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('totalItems', sa.Integer(), nullable=True),
    sa.Column('ingestedItems', sa.Integer(), nullable=True),
    sa.Column('avgSize', sa.Integer(), nullable=True),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.Column('ingestedSize', sa.Integer(), nullable=True),
    sa.Column('ingestedChunks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('instance_pipeline_step_statuses',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'FAILED', 'COMPLETED', name='pipelinestepstatus'), nullable=True),
    sa.Column('startTime', sa.String(), nullable=True),
    sa.Column('endTime', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['step'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('instance_id', 'step')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_pipeline_step_statuses')
    op.drop_table('instance_chart_data')
    op.drop_table('instances')
    op.drop_table('pipelines')
    op.drop_table('pipeline_step_dependencies')
    op.drop_table('pipeline_step_data')
    op.drop_table('pipeline_steps')
    op.drop_table('applications')
    # ### end Alembic commands ###
