import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import { ElevaiteIcons } from "@repo/ui/components";
import AppLayout from "../ui/AppLayout";
import { AppDrawerTheme } from "../ui/themes";
import Background from "./background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ElevAIte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const breadcrumbLabels: Record<string, { label: string; link: string }> = {
    appDrawer: {
      label: "Applications",
      link: "/appDrawer",
    },
    home: {
      label: "Applications",
      link: "/",
    },
  };

  const sidebarIcons: {
    linkLocation: string;
    Icon: React.ReactNode;
  }[] = [
    // { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
    // { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
    // { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
    { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/workbench" },
  ];

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-[${AppDrawerTheme.secondary}] -z-50`}>
        <AppLayout
          Background={<Background />}
          breadcrumbLabels={breadcrumbLabels}
          layout="user"
          sidebarIcons={sidebarIcons}
          theme={AppDrawerTheme}
        >
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
