import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import { ElevaiteIcons } from "@repo/ui/components";
import { SessionProvider } from "next-auth/react";
import AppLayout from "../ui/AppLayout";
import { AppDrawerTheme } from "../ui/themes";
import { auth } from "../../auth";
import Background from "./background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ElevAIte",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }): Promise<JSX.Element> {
  const breadcrumbLabels: Record<string, { label: string; link: string }> = {
    appDrawer: {
      label: "Applications",
      link: "/appDrawer",
    },
    home: {
      label: "Applications",
      link: "/",
    },
    homepage: {
      label: "Applications",
      link: "/",
    },
  };

  const sidebarIcons: {
    linkLocation: string;
    Icon: React.ReactNode;
  }[] = [
    // { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
    // { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
    // { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
    { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/workbench" },
  ];

  const session = await auth();
  if (session?.user) {
    // @ts-expect-error TODO: Look into https://react.dev/reference/react/experimental_taintObjectReference
    // filter out sensitive data before passing to client.
    session.user = {
      name: session.user.name,
      email: session.user.email,
      image: session.user.image,
    };
  }

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-[${AppDrawerTheme.secondary}] -z-50`}>
        <SessionProvider session={session}>
          <AppLayout
            Background={<Background />}
            breadcrumbLabels={breadcrumbLabels}
            layout="user"
            sidebarIcons={sidebarIcons}
            theme={AppDrawerTheme}
          >
            {children}
          </AppLayout>
        </SessionProvider>
      </body>
    </html>
  );
}
