from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime
import logging
from contextlib import asynccontextmanager
from dotenv import load_dotenv
from typing import Optional

# Import models and classes from the case models file
from case_models import (
    CaseCreationRequest,
    CaseResponse,
    CaseUpdateRequest,
    CaseCommentRequest,
    SalesforceCaseManager
)

load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Global Salesforce manager instance
sf_manager = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    global sf_manager
    sf_manager = SalesforceCaseManager()
    yield
    # Shutdown
    sf_manager = None

# FastAPI app
app = FastAPI(
    title="Salesforce Case API",
    description="API for managing Cases in Salesforce",
    version="1.0.0",
    lifespan=lifespan
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Dependency to get Salesforce manager
def get_sf_manager():
    if sf_manager is None:
        raise HTTPException(status_code=500, detail="Salesforce connection not available")
    return sf_manager

@app.get("/")
async def root():
    return {"message": "Salesforce Case API is running"}

@app.get("/health")
async def health_check(sf: SalesforceCaseManager = Depends(get_sf_manager)):
    """Health check endpoint"""
    sf_status = sf.test_connection()
    return {
        "status": "healthy" if sf_status else "unhealthy",
        "salesforce_connection": sf_status,
        "timestamp": datetime.now().isoformat()
    }

@app.post("/cases", response_model=CaseResponse)
async def create_case(
    case_request: CaseCreationRequest,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Create a new Case in Salesforce"""
    try:
        result = sf.create_case(case_request)
        
        return CaseResponse(
            id=result['id'],
            case_number=result.get('case_number', 'Generated by Salesforce'),
            status="created",
            message="Case created successfully"
        )
    except Exception as e:
        logger.error(f"Error creating Case: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/cases/{case_id}")
async def get_case(
    case_id: str,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get a specific Case by ID"""
    try:
        result = sf.get_case(case_id)
        return result
    except Exception as e:
        logger.error(f"Error retrieving Case: {str(e)}")
        raise HTTPException(status_code=404, detail="Case not found")

@app.put("/cases/{case_id}", response_model=CaseResponse)
async def update_case(
    case_id: str,
    case_update: CaseUpdateRequest,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Update an existing Case"""
    try:
        result = sf.update_case(case_id, case_update)
        return CaseResponse(
            id=case_id,
            case_number= "N/A",
            status="updated",
            message="Case updated successfully"
        )
    except Exception as e:
        logger.error(f"Error updating Case: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))



@app.get("/cases/account/{account_id}")
async def get_cases_by_account(
    account_id: str, 
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get cases associated with a specific account"""
    try:
        # Validate the account ID format
        if not sf.is_valid_salesforce_id(account_id):
            raise HTTPException(status_code=400, detail="Invalid Salesforce Account ID format")
        
        result = sf.get_cases_by_account(account_id)
        return {"records": result}
    except Exception as e:
        logger.error(f"Error fetching cases for account {account_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching cases: {str(e)}")

@app.get("/cases/contact/{contact_id}")
async def get_cases_by_contact(
    contact_id: str, 
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get cases associated with a specific contact"""
    try:
        # Validate the contact ID format
        if not sf.is_valid_salesforce_id(contact_id):
            raise HTTPException(status_code=400, detail="Invalid Salesforce Contact ID format")
        
        result = sf.get_cases_by_contact(contact_id)
        return {"records": result}
    except Exception as e:
        logger.error(f"Error fetching cases for contact {contact_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching cases: {str(e)}")


# Utility endpoints for dropdowns
@app.get("/accounts")
async def get_accounts(sf: SalesforceCaseManager = Depends(get_sf_manager)):
    """Get list of Accounts for dropdown population"""
    try:
        query = "SELECT Id, Name FROM Account ORDER BY Name LIMIT 1000"
        result = sf.sf.query(query)
        return result['records']
    except Exception as e:
        logger.error(f"Error fetching accounts: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching accounts: {str(e)}")

@app.get("/contacts")
async def get_contacts(sf: SalesforceCaseManager = Depends(get_sf_manager)):
    """Get list of Contacts for dropdown population"""
    try:
        query = """SELECT Id, Name, Email, Account.Name, AccountId
                   FROM Contact 
                   ORDER BY Name 
                   LIMIT 1000"""
        result = sf.sf.query(query)
        return result['records']
    except Exception as e:
        logger.error(f"Error fetching contacts: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching contacts: {str(e)}")

@app.get("/contacts/account/{account_id}")
async def get_contacts_by_account(
    account_id: str, 
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get contacts associated with a specific account"""
    try:
        # Validate the account ID format
        if not sf.is_valid_salesforce_id(account_id):
            raise HTTPException(status_code=400, detail="Invalid Salesforce Account ID format")
        
        query = f"""SELECT Id, Name, Email, Phone, Title
                    FROM Contact 
                    WHERE AccountId = '{account_id}'
                    ORDER BY Name
                    LIMIT 1000"""
        result = sf.sf.query(query)
        return result['records']
    except Exception as e:
        logger.error(f"Error fetching contacts for account {account_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching contacts: {str(e)}")


# CASE COMMENTS ENDPOINTS
@app.post("/cases/{case_id}/comments")
async def add_case_comment(
    case_id: str,
    comment_request: CaseCommentRequest,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Add a comment to a case"""
    try:
        result = sf.add_case_comment(case_id, comment_request)
        return {"id": result['id'], "message": "Comment added successfully"}
    except Exception as e:
        logger.error(f"Error adding comment to case {case_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/cases/{case_id}/comments")
async def get_case_comments(
    case_id: str,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get all comments for a case"""
    try:
        result = sf.get_case_comments(case_id)
        return {"records": result}
    except Exception as e:
        logger.error(f"Error fetching comments for case {case_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

# CASE MANAGEMENT ENDPOINTS
@app.post("/cases/{case_id}/escalate")
async def escalate_case(
    case_id: str,
    escalation_reason: Optional[str] = None,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Escalate a case"""
    try:
        result = sf.escalate_case(case_id, escalation_reason)
        return CaseResponse(
            id=case_id,
            case_number="N/A",
            status="escalated",
            message="Case escalated successfully"
        )
    except Exception as e:
        logger.error(f"Error escalating case {case_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/cases/{case_id}/assign/{new_owner_id}")
async def assign_case(
    case_id: str,
    new_owner_id: str,
    assignment_reason: Optional[str] = None,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Assign case to a new owner"""
    try:
        result = sf.assign_case(case_id, new_owner_id, assignment_reason)
        return CaseResponse(
            id=case_id,
            case_number="N/A",
            status="assigned",
            message="Case assigned successfully"
        )
    except Exception as e:
        logger.error(f"Error assigning case {case_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/cases/user/{user_id}")
async def get_my_cases(
    user_id: str,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get cases assigned to a specific user"""
    try:
        result = sf.get_my_cases(user_id)
        return {"records": result}
    except Exception as e:
        logger.error(f"Error fetching cases for user {user_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/cases/{case_id}/related")
async def get_related_cases(
    case_id: str,
    sf: SalesforceCaseManager = Depends(get_sf_manager)
):
    """Get related (child) cases"""
    try:
        result = sf.get_related_cases(case_id)
        return {"records": result}
    except Exception as e:
        logger.error(f"Error fetching related cases for {case_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    import os
    port = int(os.getenv('PORT', 8092))
    uvicorn.run(app, host="0.0.0.0", port=port)