import json
import os
from pprint import pprint
from dotenv import load_dotenv
from elasticsearch import Elasticsearch

from .models import ApplicationType
from .mockData import applications_list


def HelloElastic():
    # Password for the 'elastic' user generated by Elasticsearch
    load_dotenv()
    ELASTIC_PASSWORD = os.getenv("ELASTIC_PASSWORD")
    ELASTIC_SSL_FINGERPRINT = os.getenv("ELASTIC_SSL_FINGERPRINT")
    ELASTIC_HOST = os.getenv("ELASTIC_HOST")

    # Create the client instance
    client = Elasticsearch(
        ELASTIC_HOST,
        ssl_assert_fingerprint=ELASTIC_SSL_FINGERPRINT,
        basic_auth=("elastic", ELASTIC_PASSWORD),
    )

    # Successful response!
    print(client.info())
    client.options(ignore_status=[400, 404]).indices.delete(index="application")

    for application in applications_list:
        resp1 = client.index(
            index="application",
            id=application.id,
            document=json.dumps(application, default=vars),
        )
        pprint(resp1)
        pprint(resp1["result"])
