FROM python:3.11-alpine
RUN mkdir elevaite
WORKDIR /elevaite

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh


# WORKDIR /elevaite

COPY . .
WORKDIR /elevaite/workers

RUN uv sync

CMD ["uv", "run", "python", "-u", "main.py"]