FROM python:3.11-alpine
RUN mkdir elevaite
WORKDIR /elevaite

RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

# WORKDIR /elevaite

COPY . .
WORKDIR /elevaite/workers

RUN poetry install && rm -rf $POETRY_CACHE_DIR

CMD ["poetry", "run", "python", "-u", "main.py"]