FROM python:3.11-alpine
RUN mkdir elevaite
WORKDIR /elevaite
# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN uv pip install --no-cache-dir --upgrade uvicorn==0.23.2
# Install dependencies
COPY . .
WORKDIR /elevaite/rbac
RUN uv sync

WORKDIR /elevaite/rbac/rbac_api
EXPOSE 9005
ENV PORT 9005
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9005"]
