import openai

# Set your OpenAI API key
openai.api_key = "your_api_key"

# Function to generate reformulated queries using ensemble prompting
def generate_reformulated_queries(user_query, chat_history, instructions):
    """
    Generate reformulated queries using ensemble prompting.
    
    Args:
        user_query (str): The original query from the user.
        chat_history (list): List of previous chat messages for conversational context.
        instructions (list): List of paraphrased instructions for query reformulation.
        
    Returns:
        list: A list of reformulated queries generated by the LLM.
    """
    reformulated_queries = []
    
    # Combine chat history with the user query for context-aware reformulation
    conversational_context = "\n".join(chat_history)
    full_prompt_template = """
    Context:
    {context}
    
    Original Query:
    {query}
    
    Instruction:
    {instruction}
    
    Reformulate the query based on the instruction and context.
    """
    
    # Iterate through each instruction and generate reformulations
    for instruction in instructions:
        prompt = full_prompt_template.format(
            context=conversational_context,
            query=user_query,
            instruction=instruction
        )
        
        try:
            # Call the OpenAI API to generate a response
            response = openai.ChatCompletion.create(
                model="gpt-4",
                messages=[{"role": "system", "content": "You are an expert in query optimization."},
                          {"role": "user", "content": prompt}]
            )
            
            # Extract the reformulated query from the response
            reformulated_query = response['choices'][0]['message']['content'].strip()
            reformulated_queries.append(reformulated_query)
        
        except Exception as e:
            print(f"Error generating reformulation: {e}")
    
    return reformulated_queries

# Function to combine reformulated queries into a single candidate set
def combine_queries(reformulated_queries):
    """
    Combine multiple reformulated queries into a single candidate set.
    
    Args:
        reformulated_queries (list): List of reformulated queries.
        
    Returns:
        str: A single combined query string.
    """
    return " OR ".join(reformulated_queries)

# Example usage
if __name__ == "__main__":
    # User's original query
    user_query = "How to improve search engine performance?"
    
    # Last 2-3 chat history messages for conversational context
    chat_history = [
        "User: What are some techniques for optimizing search engines?",
        "Assistant: You can use techniques like query expansion, relevance feedback, and ranking algorithms."
    ]
    
    # Paraphrased instructions for ensemble prompting
    instructions = [
        "Rewrite this query to improve its clarity and relevance.",
        "Reformulate this search query to better match user intent.",
        "Generate keywords that align with the user's search intent."
    ]
    
    # Generate reformulated queries using GenQREnsemble
    reformulated_queries = generate_reformulated_queries(user_query, chat_history, instructions)
    
    # Combine the reformulated queries into a single candidate set
    final_query = combine_queries(reformulated_queries)
    
    print("Original Query:", user_query)
    print("Reformulated Queries:", reformulated_queries)
    print("Final Combined Query:", final_query)
