"""change_workflow_metrics_primary_key_to_execution_id

Revision ID: 19543a679fca
Revises: fea3946bdf5a
Create Date: 2025-08-05 18:56:16.027878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19543a679fca"
down_revision: Union[str, None] = "fea3946bdf5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Drop the primary key constraint on 'id'
    op.drop_constraint("workflow_metrics_pkey", "workflow_metrics", type_="primary")

    # Step 2: Add execution_id column (nullable first to handle existing data)
    op.add_column(
        "workflow_metrics", sa.Column("execution_id", sa.UUID(), nullable=True)
    )

    # Step 3: For any existing records, generate UUIDs for execution_id
    # (This handles the case where there might be existing data)
    op.execute(
        "UPDATE workflow_metrics SET execution_id = gen_random_uuid() WHERE execution_id IS NULL"
    )

    # Step 4: Make execution_id non-nullable and set as primary key
    op.alter_column("workflow_metrics", "execution_id", nullable=False)
    op.create_primary_key("workflow_metrics_pkey", "workflow_metrics", ["execution_id"])

    # Step 5: Drop the unique constraint on workflow_id (allow multiple executions per workflow)
    op.drop_constraint(
        "workflow_metrics_workflow_id_key", "workflow_metrics", type_="unique"
    )

    # Step 6: Drop the old id column
    op.drop_column("workflow_metrics", "id")

    # Step 7: Drop the sequence that was used by the id column
    op.execute("DROP SEQUENCE IF EXISTS workflow_metrics_id_seq")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Drop the primary key constraint on execution_id
    op.drop_constraint("workflow_metrics_pkey", "workflow_metrics", type_="primary")

    # Step 2: Create the sequence for the id column
    op.execute("CREATE SEQUENCE workflow_metrics_id_seq")

    # Step 3: Add back the id column with auto-increment
    op.add_column(
        "workflow_metrics",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('workflow_metrics_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
    )

    # Step 4: Set id as primary key
    op.create_primary_key("workflow_metrics_pkey", "workflow_metrics", ["id"])

    # Step 5: Restore unique constraint on workflow_id
    op.create_unique_constraint(
        "workflow_metrics_workflow_id_key", "workflow_metrics", ["workflow_id"]
    )

    # Step 6: Drop execution_id column
    op.drop_column("workflow_metrics", "execution_id")
    # ### end Alembic commands ###
