"""add_is_editable_field_to_workflows

Revision ID: 9330e33bc36a
Revises: 4784ab863bf6
Create Date: 2025-07-09 16:35:20.641138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9330e33bc36a"
down_revision: Union[str, None] = "4784ab863bf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column("workflows", sa.Column("is_editable", sa.Boolean(), nullable=True))

    # Set default value for existing rows (all existing workflows should be editable)
    op.execute("UPDATE workflows SET is_editable = true WHERE is_editable IS NULL")

    # Now make the column non-nullable
    op.alter_column("workflows", "is_editable", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "is_editable")
    # ### end Alembic commands ###
