"""rename metadata to step_metadata in workflow_execution_steps

Revision ID: fea3946bdf5a
Revises: 9330e33bc36a
Create Date: 2025-08-04 19:05:39.701587

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fea3946bdf5a"
down_revision: Union[str, None] = "9330e33bc36a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: The metadata -> step_metadata column rename was automatically applied
    # when the API started with the updated model definition. No manual migration needed.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename step_metadata column back to metadata in workflow_execution_steps table
    op.alter_column(
        "workflow_execution_steps", "step_metadata", new_column_name="metadata"
    )
    # ### end Alembic commands ###
