import { CommonSelectOption } from "@repo/ui/components";
import { AgentResponse, SavedWorkflow } from "./interfaces";

export const mockupWorkflows: SavedWorkflow[] = [
	{
		workflow_id: "wf-1",
		name: "Customer Support Router",
		description: "Routes customer queries to the correct internal team based on intent classification.",
		created_at: new Date().toISOString(),
		is_active: true,
		is_deployed: false,
		is_editable: true,
		version: "1.0.0",
		tags: ["Customer Support", "Routing", "Classifier"],
	},
	{
		workflow_id: "wf-2",
		name: "Multilingual Support Dispatcher",
		description: "Detects language and routes to localized agents or translation tools",
		created_at: new Date().toISOString(),
		is_active: false,
		is_deployed: false,
		is_editable: true,
		version: "1.0.0",
		tags: ["Language Detection", "Routing", "Translation"],
	},
	{
		workflow_id: "wf-3",
		name: "Invoice Data Extractor",
		description: "Extracts vendor, total, and due date from uploaded invoices.",
		created_at: new Date().toISOString(),
		is_active: false,
		is_deployed: false,
		is_editable: true,
		version: "1.0.0",
		tags: ["Document Parsing", "Finance", "Extraction"],
	},
	{
		workflow_id: "wf-4",
		name: "Contract Clause Comparator",
		description: "Compares two contract clauses and highlights legal discrepancies.",
		created_at: new Date().toISOString(),
		is_active: false,
		is_deployed: false,
		is_editable: true,
		version: "1.0.0",
		tags: ["Legal", "Comparison", "NLP"],
	},
	{
		workflow_id: "wf-5",
		name: "Refund Policy Retriever",
		description: "Answers policy questions by querying internal support documentation.",
		created_at: new Date().toISOString(),
		is_active: false,
		is_deployed: false,
		is_editable: true,
		version: "1.0.0",
		tags: ["Customer Support", "FAQ", "RAG"],
	},
]

export const mockupAgents: AgentResponse[] = [
	{
		name: "Invoice Extractor",
		system_prompt_id: "1",
		description: "Data Extractor",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	},
	{
		name: "Pricing Analyzer Agent",
		system_prompt_id: "1",
		description: "Price generator",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	},
	{
		name: "Legal Summary Bot",
		system_prompt_id: "1",
		description: "Legal Document Reader",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	},
	{
		name: "FAQ Generator",
		system_prompt_id: "1",
		description: "FAQ Routing",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	},
	{
		name: "Escalation Router Bot",
		system_prompt_id: "1",
		description: "Customer Support",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	},
	{
		name: "Escalation Router Bot",
		system_prompt_id: "1",
		description: "Customer Support",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	},
	{
		name: "Escalation Router Bot",
		system_prompt_id: "1",
		description: "Customer Support",
		functions: [],
		routing_options: { optionA: "Route to A", optionB: "Route to B" },
		short_term_memory: false,
		long_term_memory: false,
		reasoning: false,
		input_type: ["text"],
		output_type: ["text"],
		response_type: "json",
		max_retries: 3,
		deployed: true,
		status: "active",
		collaboration_mode: "single",
		available_for_deployment: true,
		id: 1,
		agent_id: "agent-1",
		system_prompt: {
			prompt_label: "Test",
			prompt: "Test",
			unique_label: "Test",
			app_name: "Test",
			version: "Test",
			ai_model_provider: "Test",
			ai_model_name: "Test",
			id: 1,
			pid: "Test",
			sha_hash: "Test",
			is_deployed: true,
			created_time: "Test",
		} ,
	}
]

export const promptTypeOptions: CommonSelectOption[] = [
	{ value: 'Extract Data' },
	{ value: 'Type2'},
];

export const promptStatusOption: CommonSelectOption[] = [
	{ value: 'Ready'},
	{ value: 'In Review'},
	{ value: 'Approved'},
];

export const promptVersionOption: CommonSelectOption[] = [
	{ value: 'V1'},
	{ value: 'V2'},
];

export const promptGroundTruthOptions: CommonSelectOption[] = [
	{ value: 'Ground Truths', disabled: true},
	{ value: 'Option 1'},
];

export const promptModelOptions: CommonSelectOption[] = [
	{ value: 'Models', disabled: true},
	{ value: 'Model 1'},
];

export const promptTokenCostPricing: CommonSelectOption[] = [
	{ value: 'Token Cost & Pricing', disabled: true},
	{ value: 'Pricing 1'},
]

export const promptDataSetOptions: CommonSelectOption[] = [
	{ value: 'Data Set', disabled: true},
	{ value: 'Data Set 1'},
];

export const promptParameterOptions: CommonSelectOption[] = [
	{ value: 'Parameters', disabled: true},
	{ value: 'Parameter 1'},
];