import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import { ElevaiteIcons } from "@repo/ui/components";
import { SessionProvider } from "next-auth/react";
import AppLayout from "../ui/AppLayout";
import { EngineerTheme } from "../ui/themes";
import { auth } from "../../auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const breadcrumbLabels: Record<string, { label: string; link: string }> = {
  workers_queues: {
    label: "Workers & Queues",
    link: "/workers_queues",
  },
  models: {
    label: "Models",
    link: "/models",
  },
  datasets: {
    label: "Datasets",
    link: "/datasets",
  },
  workbench: {
    label: "Workbench",
    link: "/workbench",
  },
  home: {
    label: "Applications",
    link: "/",
  },
};

const sidebarIcons: {
  linkLocation: string;
  Icon: React.ReactNode;
}[] = [
  // { Icon: <ElevaiteIcons.Datasets />, linkLocation: "/datasets" },
  // { Icon: <ElevaiteIcons.WorkersQueues />, linkLocation: "/workers_queues" },
  // { Icon: <ElevaiteIcons.Models />, linkLocation: "/models" },
  { Icon: <ElevaiteIcons.Workbench />, linkLocation: "/workbench" },
];

export default async function RootLayout({ children }: { children: React.ReactNode }): Promise<JSX.Element> {
  const session = await auth();
  if (session?.user) {
    // @ts-expect-error TODO: Look into https://react.dev/reference/react/experimental_taintObjectReference
    // filter out sensitive data before passing to client.
    session.user = {
      name: session.user.name,
      email: session.user.email,
      image: session.user.image,
    };
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AppLayout
            breadcrumbLabels={breadcrumbLabels}
            layout="engineer"
            sidebarIcons={sidebarIcons}
            theme={EngineerTheme}
          >
            {children}
          </AppLayout>
        </SessionProvider>
      </body>
    </html>
  );
}
